version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80

  redis:
    container_name: redis-stage
    image: redis:6.2-alpine
    command: redis-server
    restart: on-failure

  postgres:
    container_name: postgres-stage
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    volumes:
      - ./pgdata:/var/lib/data
    restart: on-failure

  next:
    container_name: next-stage
    build:
      context: ./ne
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - './ne:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postres

  node:
    container_name: node-stage
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 7890:7890
    volumes:
      - './be:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - TYPEORM_LOGGING=false
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
