version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    command: redis-server
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    volumes:
      - ./pgdata:/var/lib/data
    restart: always

  node:
    container_name: node
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - 7890:7890
    volumes:
      - './be:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - TYPEORM_HOST=postgres
      - TYPEORM_LOGGING=false
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres
    restart: always

  next:
    container_name: next
    build:
      context: ./ne
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - './ne:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postres
    restart: always
