version: '3.8'
services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    command: redis-server
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio
    volumes:
      - ./pgdata:/var/lib/data
    restart: on-failure

  node:
    container_name: node
    build:
      context: ./be
      dockerfile: Dockerfile
    volumes:
      - './be:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - TYPEORM_LOGGING=false
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres

  next:
    container_name: next
    build:
      context: ./ne
      dockerfile: Dockerfile
    volumes:
      - './ne:/usr/app'
      - '/usr/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postres

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
      - 443:433
    depends_on:
      - next
